Update cold start duration test threshold to 2 sec
I got test failure in CI:

> AssertionError: 0.6306946277618408 not less than 0.1

So it looks like in CI the hosts can be slower.

Testing:

make check
make test